import { AppSettings } from '../types';

export const DEFAULT_APP_SETTINGS: AppSettings = {
  latitude: 30.0444, // Cairo default
  longitude: 31.2357,
  cityName: 'القاهرة، مصر',
  timezoneId: 'Africa/Cairo',
  calcMethod: 'Egypt',
  madhab: 'standard',
  hijriOffset: 0,
  trackingStartDate: new Date().toISOString().split('T')[0],
  trackingStartPrayer: 'Fajr',
  hasCompletedOnboarding: false,
  theme: 'system',
  primaryCalendar: 'hijri',
  backdropStyle: 'auto',
  backdropRenderMode: 'auto',
  backdropOpacity: 60,
  cardTheme: 'dynamic',
  clockStyle: 'digital',
  cardCompactMode: false,
  gender: 'male',
  isWomenExcuse: false,
  annualKhatmaGoal: 1,
  persistentNotificationEnabled: true,
  adhanEnabled: {
    Fajr: true,
    Sunrise: true,
    Dhuhr: true,
    Asr: true,
    Maghrib: true,
    Isha: true,
  },
  prayerOffsets: {
    Fajr: 0,
    Sunrise: 0,
    Dhuhr: 0,
    Asr: 0,
    Maghrib: 0,
    Isha: 0,
  },
  prayerVolumes: {
    Fajr: 100,
    Sunrise: 100,
    Dhuhr: 100,
    Asr: 100,
    Maghrib: 100,
    Isha: 100,
  },
  pinnedWidget: {
    type: 'spiritual_card',
    theme: 'emerald_royal',
    enabled: true,
    clockStyle: 'digital',
    showMoonPhase: true,
    prayerDisplay: 'all_prayers',
    showDate: true,
    showDhikr: true,
    showAyah: true,
    showQibla: true,
    showSubhaBtn: true,
    showProgressBar: true,
    cardSize: 'medium',
  },
};
